### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by zhangbaijin** [spthermo/generative-image-inpainting#2]
Traceback (most recent call last):
  File "/generative-image-inpainting-master/main.py", line 272, in <module>
    std=[0.5, 0.5, 0.5])
  File "/home/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 209, in __init__
    is_valid_file=is_valid_file)
  File "/home/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 97, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: ./dataset/paris_streetview/train
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp

and i have resize the dataset paris_streetview to 128X128...thanks for your time

**Comment by spthermo** [comment]
@zhangbaijin it seems that you have not loaded your dataset properly. I would recommend to run the loader without any augmentation and try to print a random sample first.
